#include <stdio.h>

void printHelp(){

    char helpText[] = "Usage:\n  bcards [options]\n\nTest yourself on flashcards from the command line!\n\nOptions:\n  -d,--deck\n    Prints the deck format guide\n  -f,--file-path\n    Prints current deck save location\n  -s,--set-save\n    Set deck save location to current working directory\n  -S,--force-set-save\n    Same as --set-save but doesn't prompt for user comfirmation\n  -h,--help\n    Displays useful help text\n  -t,--tutorial\n    Prints the tutorial example deck\n\nCommands (use when running a flashcard deck):\n  :{i}\n    Skip to header number {i}\n  :h\n    List headers and display help\n  :q\n    Quit program\n  :n  \n    Skip to next header\n  :p\n    Move to previous header\n  :r\n    Restart current header\n\nTutorial:\n  Run\n    bcards -t > TUTORIAL.txt\n  in your deck save location to make the tutorial deck (can then be opened with bcards).\n\nMaking flashcard decks:\n  For help making decks run\n    bcards -d\n  or\n    bcards -d > DECKFORMATGUIDE.txt\n  and take a look\n\nMan pages are available, and Happy flashcarding!\n";

    printf(helpText);
}

void printDeckFormatGuide(){

    char deckFormatGuide[] = "h:This is a header - headers are asked in the order they appear in the file\nq:This is a question - all questions within each header are shuffled.\na:A question must be followed by an answer - like this! Answers are specific and case sensitive.\n - The line after an answer is the explanation for the answer, no specific formatting needed - everything on this line will be printed\n\n        Also as long as a line isn't following an answer and doesn't have a line type prefix, it will be ignored.\n        This means you can edit a deck file with comments like this.\n        Note: always be sure to leave a line after an answer line for the explanation. Even if you don't want to write anything in it, just leave it empty.\n        This is because anything on the line below an answer will get interpreted as the explanation, and will be printed.\n\nh:Example questions\nq:True or False: The capital of Turkey is Constantinople.\na:False\n  -> It's Istanbul not Constantinople!\nq:What was the previous name of the city now called New York.\na:New Amsterdam\n- New York was once a Dutch settlement before being taken by the English military in 1664.\n\n\nq::   <<-- be sure to never write a question like this with another colon after the q: prefix.\n            (a user will never be able to answer it because bcards will assume the user is writing a command)\n";

    printf(deckFormatGuide);
}

void printTutorial(){
    char tutorial[] = "h:Welcome to BashCards! (start here)\nq:Welcome to BashCards! Don't worry about anything printed above, but try to read all and follow from this point. By the end of this tutorial you should know all the basics and how to quiz yourself on flashcards. Type ':n' to continue.\na:You've got this\n - \nh:A BashCards deck is broken down into multiple 'headers' which contain your flashcards - this is a header!\nq:And this is a question! After any question you will be prompted to enter an answer (like right now). Lets give this a shot in header 3. Type ':n' to get there.\na:\n -\nh:Answer these example questions! When you're done, type ':n' to progress to next section.\nq:How many days are in January?\n a:31\n - One of the long ones.\nq:In what year did the Battle of Hastings take place?\na:1066\n - The battle between the Norman-French army led by William the Conqueror and the English army led by Harold Godwinson. A decisive Norman Victory.\nq:True of False? York is further north than Lancaster.\na:False\n - Lancaster is further North than York - though not by a lot! If you typed 'false', you'll realise at this point answers are case-sensitive.\nh:Introduction to commands\nq:Perfect! Now let's introduce you to commands. Whenever you are prompted for an answer, you can instead type a colon followed by a number. E.g. ':n' - you've already been using this command to skip to the next header. Use it again now!\na:\n - \nh:Further commands\nq:Commands are also very useful for navigating a deck. ':h' lists all the headers in your current deck as well as some helpful commands and ':' followed by the number of the header will skip to that one! Try using both of these to find and jump to the header 'JUMP POINT'.\na:\n -\nh:JUMP BACK\nq:You now have everything necessary to use decks and quiz yourself on flashcards! Feel free to check out any of the example decks downloaded with the program and open DECKFORMATGUIDE.txt in a text editor to see how to go about making your own decks! :n to continue.\nh:Final Word\nq:More than anything: I hope you find this project useful! If you get stuck at any point, consult the man pages or bcards --help. Best of luck learning!\nh:JUMP POINT\nq:Perfect! You can read about all available commands by running 'bcards --help' in your terminal. Now jump back to the header 'JUMP BACK' to continue the tutorial.\na:\n -\n";

    printf(tutorial);
}
